### ISSUE TITLE
[Epic] Open source

### ISSUE THREAD

**Issue by scsmithr** [GlareDB/glaredb#1004]
- [x] Update README, point to console.glaredb.com
- [x] License
- [x] Review issues, PRs, ensure no secrets or sensitive info.

# Local experience (not needed prior to open sourcing)
- [x] https://github.com/GlareDB/glaredb/issues/1008

**Comment by scsmithr** [comment]
It is done
