### ISSUE TITLE
DDL Physical Plans

### ISSUE THREAD

**Issue by scsmithr** [GlareDB/glaredb#1599]
## Description

- [x] Alter database rename - Adhish
- [x] Alter table rename - Adhish
- [x] Alter tunnel rotate keys - Adhish
- [x] Create credentials - Cory
- [x] Create external database
- [x] Create external table
- [x] Create schema - Sean
- [x] Create table - Cory
- [x] Create temp table - Adhish
- [x] Create tunnel
- [x] Create view
- [x] Drop credentials
- [x] Drop database - Adhish
- [x] Drop schemas - Adhish
- [x] Drop tables
- [x] Drop tunnel - Adhish
- [x] Drop views - Adhish

Includes creating the protobuf definitions.

**Comment by greyscaled** [comment]
Copy to and Insert into are separate (#1600, #1601) because they might be inherently more tricky than the epic here.
