### ISSUE TITLE
[Epic] support reading and writing lance file format

### ISSUE THREAD

**Issue by universalmind303** [GlareDB/glaredb#1771]
## Description

the newer lance file format offers many performance benefits over parquet, especially for random access & high cardinality predicates as well as ML operations. It would be nice if glaredb natively supported lance format

https://github.com/lancedb/lance

## Reading
- [x] https://github.com/GlareDB/glaredb/issues/2062
- [x] #2109
- [x] #2067

## Writing
- [x] #2066

## Transformation
- [ ] Add some of lance's linalg functions

## Other Work
- [x] PR upgrading datafusion dependency in Lance upstream

**Comment by tychoish** [comment]
@universalmind303 which and how many linear algebra function from lance do you think we should add? Could you list them or link to a list of them?

**Comment by tychoish** [comment]
I kind of think that we should close out this epic: our lance support is pretty complete (at least relative to our other sources), and while we might want to import more of their functions (which we could do when/as our function situation gets cleaned up), I feel like that's really an all together different project...
