### ISSUE TITLE
Epic: Distributed execution

### ISSUE THREAD

**Issue by scsmithr** [GlareDB/glaredb#1867]
## Description

See https://www.notion.so/glaredb/Distributed-Exec-f1e40e1dac174762b4f0fe4f6ac03ac9

Also see https://github.com/GlareDB/glaredb/pull/1863 (exploratory code) for some additional discussion

### Plumbing

- [x] Remove session-scoped remote sessions
  - https://www.notion.so/glaredb/Distributed-Exec-f1e40e1dac174762b4f0fe4f6ac03ac9?pvs=4#939b63d3f4c7437ea7a33d9ef1b2f054
- [ ] Create internal protobuf api
  - https://www.notion.so/glaredb/Distributed-Exec-f1e40e1dac174762b4f0fe4f6ac03ac9?pvs=4#ef265e68d1d4407391e90600cabb5294
- [x] Create scheduler
  - https://www.notion.so/glaredb/Distributed-Exec-f1e40e1dac174762b4f0fe4f6ac03ac9?pvs=4#7270e97fc4e940b19bcafa6c198b0237
  - Take a look at https://github.com/GlareDB/glaredb/blob/sean/distexec-poc/crates/rpcsrv/src/coordinator/scheduler.rs. I would also recommend putting that in `sqlexec` and not `rpcsrv`.
- [ ] (proposed) local query executor/queue consumer: 
      This should be a thread pool of worker threads that can pull tasks from a local scheduler. Worker threads will either pull locally if possible, if the local workerpool is empty, pull from remote pools.
- [ ] (proposed) move or featureflag all "local queries executed via queue consumer"
      (The query plans in the queue can be partitioned "full plans" at this point)
- [ ] (proposed) add configuration for glaredb, so that we can start a glaredb instance with information about the peers in its worker pool, and if scheduling should be enabled locally.
- [ ] (proposed) create remote query executor
      (one connection per-peer should pull jobs as worker threads are free from other peers and execute them in the same pool with other threads) 

### Planning

- [ ] Split plan into query fragments for independent execution
  - https://www.notion.so/glaredb/Distributed-Exec-f1e40e1dac174762b4f0fe4f6ac03ac9?pvs=4#8614f235f5484f03ba683fdc4c00467f

### Future work

Stuff that should be done after we have everything working.

- [ ] Cleanly drain pending tasks on shutdown
  - https://github.com/GlareDB/glaredb/pull/1863#discussion_r1342819912

**Comment by tychoish** [comment]
I added a few proposed tasks. for additional steps, after the stuff sean wrote up yesterday. Let me know if things were unclear. Also feel free to modify the proposal or the split if it doesn't make sense.)

**Comment by liurenjie1024** [comment]
Hi, is it possible to share the design doc in notion?

**Comment by tychoish** [comment]
@liurenjie1024 thanks for your interest!

> Hi, is it possible to share the design doc in notion?

Possible, yes. 

Having said that, the document in notion is pretty scattered, and I think might end up being more confusing than not, and it'll take me some time to get things into a shareable form: my inclination is to actually remove the document in notion and copy everything that's actually cogent out of the document into github issues.

In the mean time are you interested in something specific about the plan?

**Comment by liurenjie1024** [comment]
> In the mean time are you interested in something specific about the plan?

Yes, I'm a big fan of rust and datafusion, and want to help with the development of glaredb.
