### ISSUE TITLE
Chore: track bytes read/written per operation

### ISSUE THREAD

**Issue by greyscaled** [GlareDB/glaredb#1929]
## Requirements 

- We have a `Tracker` impl that pushes `event`s where they are processed and sent to our event tracker. We are focusing on extending the execution stats structure emitted for every event
  - `event`s will need to gain new fields to support using the data in this stream to support consumption tracking. 
  - as an implementation detail, this uses segment today to record the stream of events.
  - we will incrementally annotate more events with consumption data 
- An `Operation` here might emit multiple events (ex: for hybrid and/or distributed execution), to be able to aggregate (later) on a per-operation basis we will need to make sure that all events emitted from a single logical operation will have the same (unique) operation ID.

## Requirements

- add int64 fields for bytes_read and bytes_written to execution stats event stream, 
- add an operation id for every logical query/operation to execution, and add this ID to the plan context and structures. (1 : N events)
- ensure consumption events events are emitted for all compute tasks (select, copy, update, delete etc...)

## Tasks

- [x] #1901 
- [x] https://github.com/GlareDB/glaredb/pull/1928
- [x] #1931
- [ ] track egress and report as bytes_written
- [ ] ensure aggregate metrics are reported to the event tracker.

**Comment by tychoish** [comment]
remaining work:
- work to capture size of updates, delete
  (difficult because of integration with datafusion and visibility therein, but conceptually simple) 
- instrument RPC connections to add reporting
  (will work on getting some scoping information this week;)

**Comment by vrongmeal** [comment]
@greyscaled are we getting the `bytes_written` metrics now?

**Comment by greyscaled** [comment]
> @greyscaled are we getting the `bytes_written` metrics now?

yep!
