### ISSUE TITLE
feat: SQL Server followup items

### ISSUE THREAD

**Issue by scsmithr** [GlareDB/glaredb#2094]
## Description

Initial support added in https://github.com/GlareDB/glaredb/issues/2093. This lays out some follow-up items.

- [x] `read_sqlserver` function: #2310
- [x] Push down expression filters (WHERE): #2316
- [x] `datatype` table SLT tests: #2317 
- [x] Virtual schema thing (for listing tables, column info): #2311

**Comment by scsmithr** [comment]
Most of my testing was with the docker container, but there is a "glaredbtest" sql server set up on our azure account that I connected to to make sure that would work. I think you should be able to log in with your glaredb email in the azure dashboard.
