### ISSUE TITLE
[Epic]: Streamlined auth flow

### ISSUE THREAD

**Issue by greyscaled** [GlareDB/glaredb#2737]
This epic holds tickets for a 'streamlined' authentication flow whereby three main outcomes are key:

1. Clients are identified through certificates, which replaces a superfluous call to Cloud for authentication
2. Clients can store certificates for future use/streamlining
3. Clients can sign up/sign into Cloud using a familiar CLI flow

---

- [ ] #2738
- [ ] client, rpcsrv mTLS (this will close https://github.com/GlareDB/glaredb/issues/1727)
- [ ] https://github.com/GlareDB/glaredb/issues/1831 <-- this ticket context will have changed, but basically we'll be storing certificate locally
- [ ] Update response from cloud auth (TBD after above)
