### ISSUE TITLE
[Epic] JSON-backed Catalog

### ISSUE THREAD

**Issue by greyscaled** [GlareDB/glaredb#402]
Core:

- [x] #399
- [x] https://github.com/GlareDB/glaredb/issues/406
- [x] https://github.com/GlareDB/glaredb/issues/407
- [x] https://github.com/GlareDB/glaredb/issues/408
- [x] https://github.com/GlareDB/glaredb/issues/409

Affected:

- [x] #364
- [x] #353 
- [ ] https://github.com/GlareDB/glaredb/issues/352
