### ISSUE TITLE
[Epic] Initial External Tables

### ISSUE THREAD

**Issue by scsmithr** [GlareDB/glaredb#435]
- [x] https://github.com/GlareDB/glaredb/issues/139
- [x] https://github.com/GlareDB/glaredb/issues/437
- [x] https://github.com/GlareDB/glaredb/issues/487
