### ISSUE TITLE
[Epic] Metastore

### ISSUE THREAD

**Issue by scsmithr** [GlareDB/glaredb#504]
- [x] https://github.com/GlareDB/glaredb/issues/500
- [x] https://github.com/GlareDB/glaredb/issues/501
- [x] https://github.com/GlareDB/glaredb/issues/503
- [x] https://github.com/GlareDB/cloud/issues/512
- [x] https://github.com/GlareDB/glaredb/issues/519
