### ISSUE TITLE
[Epic] Connections and Datasources testing

### ISSUE THREAD

**Issue by scsmithr** [GlareDB/glaredb#517]
(Placeholder)

As we continue to add supported datasources, it's going to be increasingly important that we have a framework in place for automating tests against datasources.

- [x] Postgres https://github.com/GlareDB/glaredb/issues/433
- [x] MySQL https://github.com/GlareDB/glaredb/pull/569
- [x] Expand testing to BigQuery #684 
- [x] Expand testing to GCS/S3 Parquet #718 
- [x] #681
