### ISSUE TITLE
[Epic] Postgres compatible codec

### ISSUE THREAD

**Issue by vrongmeal** [GlareDB/glaredb#672]
A lot of different issues arose as a result of not having a Postges compatible codec. This epic can be used to keep track of each of them.

- [x] #613 
- [x] #590 
- [x] #567

### Summary

We need to implement the codec compatible with Postgres. This includes encoding and decoding the values to and from Datafusion arrays. Encoding will resolve the formatting issues as well as lay down a structure for copy statements (so we can return binary data in the future). Decoding will resolve issues that arise with querying the DB with various filters etc.

### ToDo

- [ ] Encoder
    - [ ] Supported datatypes by major datasources (`timestamp`s, `numeric`s etc.)
    - [ ] Support type hints
    - [ ] Setup SLT for all datasources: #517 
    - [ ] Other datatypes
- [ ] Decoder
    - [ ] Supported datatypes by major datasources
    - [ ] Encoder for datasources (if required) + Add test queries to datasource SLTs
    - [ ] Other datatypes
